_wandb:
    value:
        cli_version: 0.22.3
        e:
            x3b4umqtr6hm0mu1n6o3jiiz16642rqb:
                args:
                    - --model
                    - unetvae
                    - --mode
                    - train
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 128
                cpu_count_logical: 255
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "310183723008"
                        used: "118282375168"
                email: jshreeku@purdue.edu
                executable: /opt/saturncloud/envs/ece60131_proj/bin/python
                git:
                    commit: 221c19280740f1af7d6d144b319e55373625ee64
                    remote: https://github.com/JayanthShreekumar/image-colorization.git
                gpu: NVIDIA A100-SXM4-80GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-1c221f8a-5875-34e3-e6f3-d9a6c6d11e6a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-9140250e-d5f7-f4e0-823a-6b0e38f2509c
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-071f1915-63ed-fc50-d882-e7b429ce81f5
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100-SXM4-80GB
                      uuid: GPU-6f20b3e3-cc72-955a-c057-3201c529988b
                host: w-jayan-aaai2026resource2-20a8099c34294f2d9c8ca6df3345bc87z5wxb
                memory:
                    total: "2163702235136"
                os: Linux-5.15.0-210.163.7.el8uek.x86_64-x86_64-with-glibc2.35
                program: /home/jovyan/image-colorization/main.py
                python: CPython 3.12.12
                root: /home/jovyan/image-colorization
                startedAt: "2025-11-19T23:10:31.645477Z"
                writerId: x3b4umqtr6hm0mu1n6o3jiiz16642rqb
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 15
                - 16
            "4": 3.12.12
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 100
latent_dim:
    value: 256
learning_rate:
    value: 0.001
model:
    value: unetvae
seed:
    value: 8000
